version: "2"

services:
  orgpa-frontend:
    image: orgpa-frontend:latest
    restart: always
    links:
      - orgpa-database-api
    volumes:
      - ./src/orgpa-frontend:/Orgpa/src/orgpa-frontend
    ports:
      - 80:8080

  orgpa-database-api:
    image: orgpa-database-api:latest
    restart: always
    links:
      - mongo-db
    volumes:
      - ./src/orgpa-database-api:/Orgpa/src/orgpa-database-api
    ports:
      - 8000:8000

  mongo-db:
    image: mongo:4.0.3
    restart: always
    volumes:
      - ./volumes/mongo/:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./volumes/mysql/:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
        - db:db
      ports:
        - 8888:80
      environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test
      volumes:
        - /sessions
